In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train_dataset = pd.read_csv('train.csv')
print(train_dataset)

        ID   Age     BusinessTravel  DailyRate              Department  \
0        1  44.0      Travel_Rarely     1376.0         Human Resources   
1        2  25.0         Non-Travel      675.0  Research & Development   
2        3  57.0      Travel_Rarely      210.0                   Sales   
3        4  47.0      Travel_Rarely     1180.0  Research & Development   
4        5  22.0      Travel_Rarely      391.0  Research & Development   
...    ...   ...                ...        ...                     ...   
1225  1226  29.0      Travel_Rarely      806.0  Research & Development   
1226  1227  41.0      Travel_Rarely      582.0  Research & Development   
1227  1228  36.0      Travel_Rarely     1456.0                   Sales   
1228  1229  23.0      Travel_Rarely      885.0  Research & Development   
1229  1230  31.0  Travel_Frequently      754.0                   Sales   

      DistanceFromHome  Gender  HourlyRate  JobInvolvement  JobLevel  ...  \
0                    1    Male    

In [3]:
X = train_dataset.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,22,23,24,25,26,28,29,30,31,32,35,36,37,38,39,41]].values

In [4]:
print(X)
print(X[0])
print(X[1])
print(len(X[0]))


[[44.0 'Travel_Rarely' 1376.0 ... 3.0 6 15.0]
 [25.0 'Non-Travel' 675.0 ... 1.0 5 7.0]
 [57.0 'Travel_Rarely' 210.0 ... 0.0 0 3.0]
 ...
 [36.0 'Travel_Rarely' 1456.0 ... 2.0 2 15.0]
 [23.0 'Travel_Rarely' 885.0 ... 0.0 2 15.0]
 [31.0 'Travel_Frequently' 754.0 ... 0.0 8 11.0]]
[44.0 'Travel_Rarely' 1376.0 'Human Resources' 1 'Male' 91.0 2.0 3
 'Human Resources' 1.0 'Married' 10482 2326.0 9.0 'No' 14.0 3 4 46116 4.0
 9632 9 4.0 1 24.0 1 2.0 'Medical' 2.0 3.0 6 3.0 6 15.0]
[25.0 'Non-Travel' 675.0 'Research & Development' 5 'Male' 85.0 4.0 2
 'Healthcare Representative' 1.0 'Divorced' 4000 18384.0 1.0 'No' 12.0 3 5
 10635 6.0 4725 7 4.0 2 6.0 2 2.0 'Life Sciences' 2.0 3.0 3 1.0 5 7.0]
35


In [5]:
y = train_dataset.iloc[:, [-2,-1]].values
print(y)

[[ 1 20]
 [ 0  6]
 [ 0  1]
 ...
 [ 1  2]
 [ 0  3]
 [ 1 10]]


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# creating the object of the simpleImputer class to replace our missing with the mean
imputer.fit(X[:, [0,2,6,7,10,13,14,16,20,23,25,27,29,30,32,34]])
print(X)
# we use the fit function to fit the imputer on the data set
X[:, [0,2,6,7,10,13,14,16,20,23,25,27,29,30,32,34]
] = np.round(imputer.transform(X[:,[0,2,6,7,10,13,14,16,20,23,25,27,29,30,32,34]
]))
# using the tranform function we are actually replacing the missing values

[[44.0 'Travel_Rarely' 1376.0 ... 3.0 6 15.0]
 [25.0 'Non-Travel' 675.0 ... 1.0 5 7.0]
 [57.0 'Travel_Rarely' 210.0 ... 0.0 0 3.0]
 ...
 [36.0 'Travel_Rarely' 1456.0 ... 2.0 2 15.0]
 [23.0 'Travel_Rarely' 885.0 ... 0.0 2 15.0]
 [31.0 'Travel_Frequently' 754.0 ... 0.0 8 11.0]]


In [7]:
print(X[215])

[35.0 'Travel_Rarely' 794.0 'Research & Development' 10 'Female' 51.0 3.0
 2 'Healthcare Representative' 3.0 'Single' 6142 4223.0 3.0 'Yes' 16.0 3 2
 32360 4.0 4690 8 3.0 0 10.0 4 4.0 'Medical' 1.0 3.0 2 0.0 4 13.0]


In [8]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,3,5,9,11,15,28])], remainder='passthrough')
# # transformers -->   list of tuple ('name', transformer, column_on_which_to_be_applied)
# # here remainder : default ='drop'
# # creating the object for ColumnTransformer with onehotencoder for 1st column
# X = np.array(ct.fit_transform(X))
# # fitting and tranformer the initial data set and then converting it into a numpy array.

In [9]:
#label encoder

print(type(X))

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X[:, 1] = le.fit_transform(X[:, 1])
X[:, 3] = le.fit_transform(X[:, 3])
X[:, 5] = le.fit_transform(X[:, 5])
X[:, 9] = le.fit_transform(X[:, 9])
X[:, 11] = le.fit_transform(X[:, 11])
X[:, 15] = le.fit_transform(X[:, 15])
X[:, 28] = le.fit_transform(X[:, 28])
# for column in X.columns:
#     if X[column].dtype == np.number:
#         continue
#     X[column] = LabelEncoder().fit_transform(X[column])

print(X[0])
print(X[1])

<class 'numpy.ndarray'>
[44.0 2 1376.0 0 1 1 91.0 2.0 3 1 1.0 1 10482 2326.0 9.0 0 14.0 3 4 46116
 4.0 9632 9 4.0 1 24.0 1 2.0 3 2.0 3.0 6 3.0 6 15.0]
[25.0 0 675.0 1 5 1 85.0 4.0 2 0 1.0 0 4000 18384.0 1.0 0 12.0 3 5 10635
 6.0 4725 7 4.0 2 6.0 2 2.0 1 2.0 3.0 3 1.0 5 7.0]


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.25,random_state = 10)

In [11]:
# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler()
# x_train = sc.fit_transform(x_train)
# x_test = sc.transform(x_test)

In [12]:
print(y_train)

[[0 4]
 [0 1]
 [0 5]
 ...
 [1 8]
 [1 0]
 [0 9]]


In [13]:
y0 = []
y1 = []
for i in y_train:
    y0.append(i[0])
    y1.append(i[1])

In [14]:
from sklearn.ensemble import RandomForestClassifier
cl = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
cl.fit(x_train, y0)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [15]:
print(y_test)

[[ 0  8]
 [ 0  5]
 [ 1 10]
 [ 0  5]
 [ 0  9]
 [ 0  3]
 [ 0 25]
 [ 0 10]
 [ 0  5]
 [ 0  8]
 [ 0  8]
 [ 0  2]
 [ 0  2]
 [ 0  6]
 [ 1  1]
 [ 0  9]
 [ 1  8]
 [ 0  7]
 [ 0  8]
 [ 0  1]
 [ 0  8]
 [ 0 11]
 [ 1  2]
 [ 0  2]
 [ 0  1]
 [ 0  5]
 [ 0  2]
 [ 0  9]
 [ 0  5]
 [ 0  2]
 [ 0  1]
 [ 1  1]
 [ 0  6]
 [ 0  3]
 [ 0  3]
 [ 0  1]
 [ 0  1]
 [ 1 11]
 [ 0  5]
 [ 0  5]
 [ 0  4]
 [ 0 14]
 [ 0  2]
 [ 0  8]
 [ 0  3]
 [ 0  7]
 [ 0  8]
 [ 0  5]
 [ 0  1]
 [ 1  7]
 [ 0  8]
 [ 0  2]
 [ 0 10]
 [ 0 10]
 [ 0  2]
 [ 0  2]
 [ 0 20]
 [ 0  6]
 [ 0  9]
 [ 0  9]
 [ 0  4]
 [ 0  2]
 [ 0 18]
 [ 0 19]
 [ 0  5]
 [ 0 12]
 [ 0 13]
 [ 0  1]
 [ 0 24]
 [ 0  1]
 [ 0  4]
 [ 0  1]
 [ 0  4]
 [ 1  3]
 [ 1  8]
 [ 0  5]
 [ 0 21]
 [ 1 10]
 [ 0  5]
 [ 0  5]
 [ 0 18]
 [ 0  5]
 [ 0  1]
 [ 0 10]
 [ 0  2]
 [ 0  5]
 [ 0  4]
 [ 0  3]
 [ 0 13]
 [ 1  9]
 [ 0 20]
 [ 0  5]
 [ 1  2]
 [ 1  4]
 [ 0  4]
 [ 0 10]
 [ 0  5]
 [ 0 10]
 [ 0  5]
 [ 0  2]
 [ 0  9]
 [ 0 15]
 [ 0  2]
 [ 0  8]
 [ 0  3]
 [ 0  5]
 [ 1  4]
 [ 0 12]
 [ 0 22]
 [ 0 15]
 [ 0  6]
 

In [16]:
y2 = []
y3 = []
for i in y_test:
    y2.append(i[0])
    y3.append(i[1])

In [17]:
y_pred = cl.predict(x_test)
print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0]


In [18]:
y_pred1 = cl.predict_proba(x_test)
print(y_pred1)

[[0.69 0.31]
 [0.81 0.19]
 [0.86 0.14]
 [0.97 0.03]
 [0.95 0.05]
 [0.79 0.21]
 [0.93 0.07]
 [0.91 0.09]
 [0.9  0.1 ]
 [0.88 0.12]
 [0.88 0.12]
 [0.84 0.16]
 [0.71 0.29]
 [0.88 0.12]
 [0.53 0.47]
 [0.96 0.04]
 [0.8  0.2 ]
 [0.83 0.17]
 [0.89 0.11]
 [0.94 0.06]
 [0.91 0.09]
 [0.81 0.19]
 [0.55 0.45]
 [0.87 0.13]
 [0.76 0.24]
 [0.87 0.13]
 [0.79 0.21]
 [0.81 0.19]
 [0.87 0.13]
 [0.87 0.13]
 [0.56 0.44]
 [0.32 0.68]
 [0.79 0.21]
 [0.79 0.21]
 [0.73 0.27]
 [0.91 0.09]
 [0.9  0.1 ]
 [0.84 0.16]
 [0.92 0.08]
 [0.85 0.15]
 [0.93 0.07]
 [1.   0.  ]
 [0.61 0.39]
 [0.89 0.11]
 [0.74 0.26]
 [0.92 0.08]
 [0.86 0.14]
 [0.94 0.06]
 [0.84 0.16]
 [0.97 0.03]
 [0.56 0.44]
 [0.87 0.13]
 [0.95 0.05]
 [0.74 0.26]
 [0.58 0.42]
 [0.67 0.33]
 [0.9  0.1 ]
 [0.97 0.03]
 [0.88 0.12]
 [0.78 0.22]
 [0.89 0.11]
 [0.71 0.29]
 [0.89 0.11]
 [0.95 0.05]
 [0.73 0.27]
 [0.97 0.03]
 [1.   0.  ]
 [0.64 0.36]
 [0.92 0.08]
 [0.86 0.14]
 [0.93 0.07]
 [0.56 0.44]
 [0.95 0.05]
 [0.83 0.17]
 [0.52 0.48]
 [0.78 0.22]
 [0.89 0.11]

In [19]:
proans = []
for i in y_pred1:
    proans.append(i[1])
print(proans)

[0.31, 0.19, 0.14, 0.03, 0.05, 0.21, 0.07, 0.09, 0.1, 0.12, 0.12, 0.16, 0.29, 0.12, 0.47, 0.04, 0.2, 0.17, 0.11, 0.06, 0.09, 0.19, 0.45, 0.13, 0.24, 0.13, 0.21, 0.19, 0.13, 0.13, 0.44, 0.68, 0.21, 0.21, 0.27, 0.09, 0.1, 0.16, 0.08, 0.15, 0.07, 0.0, 0.39, 0.11, 0.26, 0.08, 0.14, 0.06, 0.16, 0.03, 0.44, 0.13, 0.05, 0.26, 0.42, 0.33, 0.1, 0.03, 0.12, 0.22, 0.11, 0.29, 0.11, 0.05, 0.27, 0.03, 0.0, 0.36, 0.08, 0.14, 0.07, 0.44, 0.05, 0.17, 0.48, 0.22, 0.11, 0.16, 0.19, 0.24, 0.13, 0.16, 0.42, 0.26, 0.16, 0.31, 0.04, 0.25, 0.06, 0.03, 0.05, 0.03, 0.27, 0.2, 0.32, 0.24, 0.26, 0.03, 0.16, 0.1, 0.02, 0.06, 0.16, 0.27, 0.23, 0.06, 0.17, 0.04, 0.1, 0.05, 0.15, 0.16, 0.06, 0.17, 0.09, 0.26, 0.11, 0.12, 0.1, 0.24, 0.13, 0.18, 0.06, 0.12, 0.05, 0.11, 0.3, 0.02, 0.14, 0.1, 0.14, 0.11, 0.16, 0.45, 0.33, 0.03, 0.08, 0.35, 0.13, 0.31, 0.33, 0.07, 0.41, 0.08, 0.16, 0.14, 0.27, 0.06, 0.04, 0.31, 0.46, 0.18, 0.35, 0.26, 0.25, 0.1, 0.07, 0.18, 0.1, 0.08, 0.09, 0.17, 0.18, 0.14, 0.04, 0.15, 0.07, 0.11, 0.12,

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y2, y_pred)
print(cm)
accuracy_score(y2, y_pred)

[[265   1]
 [ 38   4]]


0.8733766233766234

In [21]:
import sklearn.metrics as met
mse = met.mean_squared_error(y2, y_pred)
print('MSE : ', mse )
r2 = met.r2_score(y2, y_pred)
print('R-square_score: ', r2)
rmse = np.sqrt(mse)
print('RMSE :', rmse )

MSE :  0.1266233766233766
R-square_score:  -0.07518796992481169
RMSE : 0.3558417859433833


## Test data attrition

In [22]:
test_dataset = pd.read_csv('test.csv')
print(test_dataset.head())

   ID  Age BusinessTravel  DailyRate              Department  \
0   1   27  Travel_Rarely        591  Research & Development   
1   2   26  Travel_Rarely       1443                   Sales   
2   3   50  Travel_Rarely        328  Research & Development   
3   4   41  Travel_Rarely       1102                   Sales   
4   5   28  Travel_Rarely        440  Research & Development   

   DistanceFromHome  Gender  HourlyRate  JobInvolvement  JobLevel  ...  \
0                 2    Male          40               3         1  ...   
1                23  Female          47               2         2  ...   
2                 1    Male          86               2         1  ...   
3                 1  Female          94               3         2  ...   
4                21    Male          42               3         1  ...   

  EducationField  EmployeeCount EmployeeNumber  EnvironmentSatisfaction  \
0        Medical              1            7.0                        1   
1      Marketing    

In [23]:
X1 = test_dataset.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,22,23,24,25,26,28,29,30,31,32,35,36,37,38,39,41]].values

In [24]:
print(X1[1])
print(len(X1[0]))

[26 'Travel_Rarely' 1443 'Sales' 23 'Female' 47 2 2 'Sales Executive' 4
 'Married' 4157 21436 7 'Yes' 19 3.0 3 8157.0 2 10101 0 3 1.0 5 2 3
 'Marketing' 3 2 2 0 0 30.0]
35


In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# creating the object of the simpleImputer class to replace our missing with the mean
imputer.fit(X1[:, [17,19,24,34]])

# we use the fit function to fit the imputer on the data set
X1[:, [17,19,24,34]] = np.round(imputer.transform(X1[:,[17,19,24,34]]))
# using the tranform function we are actually replacing the missing values

In [26]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X1[:, 1] = le.fit_transform(X1[:, 1])
X1[:, 3] = le.fit_transform(X1[:, 3])
X1[:, 5] = le.fit_transform(X1[:, 5])
X1[:, 9] = le.fit_transform(X1[:, 9])
X1[:, 11] = le.fit_transform(X1[:, 11])
X1[:, 15] = le.fit_transform(X1[:, 15])
X1[:, 28] = le.fit_transform(X1[:, 28])
# for column in X.columns:
#     if X[column].dtype == np.number:
#         continue
#     X[column] = LabelEncoder().fit_transform(X[column])

print(X1[0])
print(X1[1])

[27 2 591 1 2 1 40 3 1 2 2 1 3468 16632 9 0 12 3.0 1 26931.0 3 4137 1 4
 1.0 6 3 1 3 1 3 2 2 2 14.0]
[26 2 1443 2 23 0 47 2 2 7 4 1 4157 21436 7 1 19 3.0 3 8157.0 2 10101 0 3
 1.0 5 2 3 2 3 2 2 0 0 30.0]


In [27]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,3,5,9,11,15,28])], remainder='passthrough')
# # transformers -->   list of tuple ('name', transformer, column_on_which_to_be_applied)
# # here remainder : default ='drop'
# # creating the object for ColumnTransformer with onehotencoder for 1st column
# X1 = np.array(ct.fit_transform(X1))
# # fitting and tranformer the initial data set and then converting it into a numpy array.

In [28]:
# X1 = sc.fit_transform(X1)

In [29]:
print(X1)

[[27 2 591 ... 2 2 14.0]
 [26 2 1443 ... 0 0 30.0]
 [50 2 328 ... 0 2 3.0]
 ...
 [37 0 1040 ... 0 0 10.0]
 [44 0 489 ... 1 2 7.0]
 [28 2 1434 ... 2 2 28.0]]


In [30]:
y_predtest1 = cl.predict(X1)
print(y_predtest1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [31]:
y_predprotest1 = cl.predict_proba(X1)
print(y_predprotest1)

[[0.81 0.19]
 [0.65 0.35]
 [0.95 0.05]
 [0.67 0.33]
 [0.83 0.17]
 [0.7  0.3 ]
 [0.79 0.21]
 [0.94 0.06]
 [0.95 0.05]
 [0.9  0.1 ]
 [0.85 0.15]
 [0.73 0.27]
 [0.74 0.26]
 [0.61 0.39]
 [0.99 0.01]
 [0.82 0.18]
 [0.69 0.31]
 [0.87 0.13]
 [0.89 0.11]
 [0.84 0.16]
 [0.87 0.13]
 [0.81 0.19]
 [0.48 0.52]
 [0.75 0.25]
 [0.88 0.12]
 [0.8  0.2 ]
 [0.72 0.28]
 [0.82 0.18]
 [0.82 0.18]
 [0.91 0.09]
 [0.6  0.4 ]
 [0.64 0.36]
 [0.76 0.24]
 [0.73 0.27]
 [0.93 0.07]
 [0.67 0.33]
 [0.79 0.21]
 [0.97 0.03]
 [0.91 0.09]
 [0.97 0.03]
 [0.99 0.01]
 [0.96 0.04]
 [0.83 0.17]
 [0.87 0.13]
 [0.91 0.09]
 [0.79 0.21]
 [0.82 0.18]
 [0.79 0.21]
 [0.52 0.48]
 [0.78 0.22]
 [0.93 0.07]
 [0.56 0.44]
 [0.81 0.19]
 [0.74 0.26]
 [0.98 0.02]
 [0.38 0.62]
 [0.71 0.29]
 [0.96 0.04]
 [0.76 0.24]
 [0.98 0.02]
 [0.96 0.04]
 [0.92 0.08]
 [0.78 0.22]
 [0.9  0.1 ]
 [0.83 0.17]
 [0.79 0.21]
 [0.84 0.16]
 [0.96 0.04]
 [0.92 0.08]
 [0.69 0.31]
 [0.87 0.13]
 [0.58 0.42]
 [0.91 0.09]
 [0.68 0.32]
 [0.94 0.06]
 [0.82 0.18]
 [0.64 0.36]

In [32]:
proans1 = []
for i in y_predprotest1:
    proans1.append(round(i[1],2))
print(proans1)

[0.19, 0.35, 0.05, 0.33, 0.17, 0.3, 0.21, 0.06, 0.05, 0.1, 0.15, 0.27, 0.26, 0.39, 0.01, 0.18, 0.31, 0.13, 0.11, 0.16, 0.13, 0.19, 0.52, 0.25, 0.12, 0.2, 0.28, 0.18, 0.18, 0.09, 0.4, 0.36, 0.24, 0.27, 0.07, 0.33, 0.21, 0.03, 0.09, 0.03, 0.01, 0.04, 0.17, 0.13, 0.09, 0.21, 0.18, 0.21, 0.48, 0.22, 0.07, 0.44, 0.19, 0.26, 0.02, 0.62, 0.29, 0.04, 0.24, 0.02, 0.04, 0.08, 0.22, 0.1, 0.17, 0.21, 0.16, 0.04, 0.08, 0.31, 0.13, 0.42, 0.09, 0.32, 0.06, 0.18, 0.36, 0.06, 0.26, 0.53, 0.07, 0.29, 0.35, 0.15, 0.07, 0.21, 0.1, 0.35, 0.06, 0.09, 0.01, 0.14, 0.12, 0.22, 0.03, 0.28, 0.13, 0.09, 0.64, 0.12, 0.13, 0.25, 0.08, 0.07, 0.25, 0.21, 0.12, 0.11, 0.23, 0.05, 0.11, 0.19, 0.09, 0.31, 0.1, 0.09, 0.06, 0.12, 0.2, 0.14, 0.07, 0.29, 0.11, 0.24, 0.05, 0.21, 0.15, 0.04, 0.27, 0.07, 0.23, 0.16, 0.15, 0.11, 0.2, 0.18, 0.16, 0.04, 0.09, 0.15, 0.06, 0.14, 0.39, 0.6, 0.05, 0.1, 0.08, 0.41, 0.1, 0.02, 0.11, 0.15, 0.08, 0.2, 0.21, 0.13, 0.3, 0.13, 0.07, 0.39, 0.17, 0.29, 0.03, 0.2, 0.07, 0.09, 0.12, 0.16, 0.49, 

#   YEARS AT COMPANY

In [33]:
print(y1)

[4, 1, 5, 25, 15, 6, 10, 10, 11, 2, 9, 10, 1, 3, 1, 8, 10, 3, 9, 1, 5, 8, 10, 3, 5, 1, 8, 5, 3, 10, 22, 2, 10, 2, 1, 3, 8, 22, 3, 9, 2, 2, 10, 9, 7, 2, 7, 4, 30, 15, 8, 9, 10, 5, 8, 15, 21, 10, 9, 7, 2, 6, 1, 16, 1, 7, 1, 0, 10, 5, 1, 3, 2, 5, 3, 11, 5, 18, 19, 3, 14, 5, 20, 4, 10, 3, 3, 13, 1, 10, 5, 3, 9, 4, 10, 4, 1, 2, 6, 3, 10, 1, 5, 0, 2, 7, 8, 10, 8, 4, 6, 2, 10, 4, 2, 4, 1, 3, 4, 8, 1, 9, 5, 1, 9, 9, 2, 13, 6, 8, 8, 2, 4, 3, 8, 6, 5, 10, 22, 8, 6, 3, 16, 2, 7, 7, 7, 3, 1, 2, 7, 8, 3, 4, 0, 8, 31, 10, 8, 19, 5, 10, 5, 3, 19, 3, 3, 6, 7, 2, 7, 1, 9, 1, 2, 1, 4, 3, 5, 0, 4, 0, 8, 3, 5, 10, 4, 4, 1, 11, 5, 5, 3, 8, 1, 8, 24, 5, 1, 0, 4, 2, 5, 6, 1, 7, 5, 6, 1, 9, 10, 5, 5, 5, 1, 3, 5, 5, 0, 6, 26, 5, 36, 9, 3, 6, 1, 5, 11, 15, 1, 9, 6, 1, 5, 3, 5, 1, 2, 1, 1, 2, 4, 3, 4, 1, 10, 3, 3, 2, 0, 5, 6, 7, 1, 3, 6, 3, 9, 3, 8, 1, 2, 3, 13, 13, 2, 18, 12, 4, 10, 1, 5, 21, 2, 7, 2, 15, 5, 0, 1, 9, 8, 8, 8, 6, 31, 3, 14, 5, 21, 5, 5, 3, 10, 4, 9, 0, 5, 5, 4, 6, 10, 8, 34, 1, 5, 9, 18, 20, 8, 

In [34]:
# import the regressor
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 200, random_state = 0)
regressor.fit(x_train, y1)  

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=200, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [35]:
y_predyears = regressor.predict(x_test)
y_predyears = np.round(y_predyears, decimals=0)
#print(y_predyears)
print(np.concatenate((y_predyears.reshape(len(y_predyears),1), (np.array(y3)).reshape(len(y3),1)),1))

[[ 8.  8.]
 [ 5.  5.]
 [10. 10.]
 [ 7.  5.]
 [10.  9.]
 [ 3.  3.]
 [24. 25.]
 [ 8. 10.]
 [ 5.  5.]
 [ 9.  8.]
 [ 9.  8.]
 [ 3.  2.]
 [ 3.  2.]
 [ 7.  6.]
 [ 1.  1.]
 [ 9.  9.]
 [ 8.  8.]
 [ 8.  7.]
 [ 8.  8.]
 [ 1.  1.]
 [ 8.  8.]
 [11. 11.]
 [ 3.  2.]
 [ 2.  2.]
 [ 1.  1.]
 [ 5.  5.]
 [ 3.  2.]
 [ 9.  9.]
 [ 5.  5.]
 [ 3.  2.]
 [ 1.  1.]
 [ 1.  1.]
 [ 5.  6.]
 [ 3.  3.]
 [ 3.  3.]
 [ 1.  1.]
 [ 1.  1.]
 [11. 11.]
 [ 5.  5.]
 [ 5.  5.]
 [ 5.  4.]
 [14. 14.]
 [ 4.  2.]
 [ 8.  8.]
 [ 4.  3.]
 [15.  7.]
 [10.  8.]
 [ 5.  5.]
 [ 1.  1.]
 [ 8.  7.]
 [ 8.  8.]
 [ 2.  2.]
 [11. 10.]
 [10. 10.]
 [ 2.  2.]
 [ 2.  2.]
 [22. 20.]
 [ 5.  6.]
 [ 8.  9.]
 [ 9.  9.]
 [ 5.  4.]
 [ 3.  2.]
 [15. 18.]
 [18. 19.]
 [ 6.  5.]
 [13. 12.]
 [12. 13.]
 [ 1.  1.]
 [11. 24.]
 [ 0.  1.]
 [ 5.  4.]
 [ 1.  1.]
 [ 4.  4.]
 [ 4.  3.]
 [ 8.  8.]
 [ 5.  5.]
 [20. 21.]
 [11. 10.]
 [ 5.  5.]
 [ 5.  5.]
 [16. 18.]
 [ 5.  5.]
 [ 1.  1.]
 [10. 10.]
 [ 2.  2.]
 [ 5.  5.]
 [ 5.  4.]
 [ 2.  3.]
 [ 9. 13.]
 [ 8.  9.]
 [21. 20.]

In [36]:
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(y3, y_predyears), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y3, y_predyears), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(y3, y_predyears), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(y3, y_predyears), 2)) 
print("R2 score =", round(sm.r2_score(y3, y_predyears), 2))

Mean absolute error = 0.73
Mean squared error = 2.45
Median absolute error = 0.0
Explain variance score = 0.92
R2 score = 0.92


In [37]:
import sklearn.metrics as met
mse = met.mean_squared_error(y3, y_predyears)
print('MSE : ', mse )
r2 = met.r2_score(y3, y_predyears)
print('R-square_score: ', r2)
rmse = np.sqrt(mse)
print('RMSE :', rmse )

MSE :  2.4512987012987013
R-square_score:  0.9246745203321136
RMSE : 1.5656623841999595


## Test DATA YearAtCompany

In [38]:
X2 = test_dataset.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,22,23,24,25,26,28,29,30,31,32,35,36,37,38,39,41]].values

In [39]:
print(X2[1])
print(len(X2[0]))

[26 'Travel_Rarely' 1443 'Sales' 23 'Female' 47 2 2 'Sales Executive' 4
 'Married' 4157 21436 7 'Yes' 19 3.0 3 8157.0 2 10101 0 3 1.0 5 2 3
 'Marketing' 3 2 2 0 0 30.0]
35


In [41]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# creating the object of the simpleImputer class to replace our missing with the mean
imputer.fit(X2[:, [17,19,24,34]])

# we use the fit function to fit the imputer on the data set
X2[:, [17,19,24,34]] = np.round(imputer.transform(X2[:,[17,19,24,34]]))
# using the tranform function we are actually replacing the missing values

In [42]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X2[:, 1] = le.fit_transform(X2[:, 1])
X2[:, 3] = le.fit_transform(X2[:, 3])
X2[:, 5] = le.fit_transform(X2[:, 5])
X2[:, 9] = le.fit_transform(X2[:, 9])
X2[:, 11] = le.fit_transform(X2[:, 11])
X2[:, 15] = le.fit_transform(X2[:, 15])
X2[:, 28] = le.fit_transform(X2[:, 28])
# for column in X.columns:
#     if X[column].dtype == np.number:
#         continue
#     X[column] = LabelEncoder().fit_transform(X[column])

print(X2[0])
print(X2[1])

[27 2 591 1 2 1 40 3 1 2 2 1 3468 16632 9 0 12 3.0 1 26931.0 3 4137 1 4
 1.0 6 3 1 3 1 3 2 2 2 14.0]
[26 2 1443 2 23 0 47 2 2 7 4 1 4157 21436 7 1 19 3.0 3 8157.0 2 10101 0 3
 1.0 5 2 3 2 3 2 2 0 0 30.0]


In [43]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,3,5,9,11,15,28])], remainder='passthrough')
# # transformers -->   list of tuple ('name', transformer, column_on_which_to_be_applied)
# # here remainder : default ='drop'
# # creating the object for ColumnTransformer with onehotencoder for 1st column
# X2 = np.array(ct.fit_transform(X2))
# # fitting and tranformer the initial data set and then converting it into a numpy array.

In [44]:
# X2 = sc.fit_transform(X2)

In [45]:
y_predtest2 = regressor.predict(X2)
y_predtest2 = np.round(y_predtest2, decimals=0)
print(y_predtest2)

[ 3.  4.  3.  6.  4.  2.  6.  5. 15.  3.  2.  5.  3.  1. 14.  5.  2.  4.
  3.  5. 11.  8.  1.  4.  1.  4.  8.  7.  2.  5.  5.  1.  1.  2. 13.  1.
 10.  5.  2.  6. 16. 13.  8. 32.  3.  1.  4.  1.  1.  5.  9.  9.  8.  2.
  8.  0. 33. 11.  5. 21. 10. 10.  9.  4. 18.  1. 11. 10. 12.  2. 16.  1.
 23.  8.  5.  5.  1. 20.  3.  5.  7.  5.  3. 18. 17.  2.  9.  3. 21. 18.
 16.  8.  5.  2. 10.  1.  5. 32.  1. 11.  8. 10. 13. 10.  4.  3. 31.  1.
  5. 10.  8.  5. 10. 10. 13.  8. 13. 10.  3.  2.  2.  1. 15. 22.  8.  1.
  6.  8.  1.  5.  1.  2. 11. 12.  5. 11. 15.  6. 24.  2.  8. 10.  2.  1.
 18. 13.  9.  3.  5. 14.  6.  5. 20. 12.  9.  9.  3. 10.  5.  3.  6.  1.
  9.  4.  7.  1. 22.  5.  1.  1.  6. 10.  1.  6. 11.  1.  5. 15.  5. 21.
 14. 12.  1.  5. 17.  8.  1.  1.  5.  2.  5.  5.  1.  9.  9.  5.  8.  5.
 10.  8.  2.  8.  5.  5.  8.  1.  3.  5. 17.  6.  6.  8. 11.  3.  5. 10.
 10.  1.  4.  9.  5. 17. 10.  4.  4. 10. 18.  2.  3.  5. 10.  0. 10.  5.
 11.  1.  5.  1.  3.  2.]


# Analysis

In [46]:
print(len(proans1))

240


In [47]:
print(proans1)

[0.19, 0.35, 0.05, 0.33, 0.17, 0.3, 0.21, 0.06, 0.05, 0.1, 0.15, 0.27, 0.26, 0.39, 0.01, 0.18, 0.31, 0.13, 0.11, 0.16, 0.13, 0.19, 0.52, 0.25, 0.12, 0.2, 0.28, 0.18, 0.18, 0.09, 0.4, 0.36, 0.24, 0.27, 0.07, 0.33, 0.21, 0.03, 0.09, 0.03, 0.01, 0.04, 0.17, 0.13, 0.09, 0.21, 0.18, 0.21, 0.48, 0.22, 0.07, 0.44, 0.19, 0.26, 0.02, 0.62, 0.29, 0.04, 0.24, 0.02, 0.04, 0.08, 0.22, 0.1, 0.17, 0.21, 0.16, 0.04, 0.08, 0.31, 0.13, 0.42, 0.09, 0.32, 0.06, 0.18, 0.36, 0.06, 0.26, 0.53, 0.07, 0.29, 0.35, 0.15, 0.07, 0.21, 0.1, 0.35, 0.06, 0.09, 0.01, 0.14, 0.12, 0.22, 0.03, 0.28, 0.13, 0.09, 0.64, 0.12, 0.13, 0.25, 0.08, 0.07, 0.25, 0.21, 0.12, 0.11, 0.23, 0.05, 0.11, 0.19, 0.09, 0.31, 0.1, 0.09, 0.06, 0.12, 0.2, 0.14, 0.07, 0.29, 0.11, 0.24, 0.05, 0.21, 0.15, 0.04, 0.27, 0.07, 0.23, 0.16, 0.15, 0.11, 0.2, 0.18, 0.16, 0.04, 0.09, 0.15, 0.06, 0.14, 0.39, 0.6, 0.05, 0.1, 0.08, 0.41, 0.1, 0.02, 0.11, 0.15, 0.08, 0.2, 0.21, 0.13, 0.3, 0.13, 0.07, 0.39, 0.17, 0.29, 0.03, 0.2, 0.07, 0.09, 0.12, 0.16, 0.49, 

In [48]:
print(len(y_predtest2))

240


In [49]:
ids = test_dataset.iloc[:,0].values
print(ids)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240]


In [50]:
print(type(proans1),len(proans1))
proans1 = np.array(proans1)
print(type(proans1),len(proans1))
print(type(y_predtest2), len(y_predtest2))
print(type(ids), len(ids))

<class 'list'> 240
<class 'numpy.ndarray'> 240
<class 'numpy.ndarray'> 240
<class 'numpy.ndarray'> 240


In [51]:
import csv
head = {
         1:'ID',
         2:'Attrition',
         3:'YearsAtCompany'
    }

file = open('trial1.csv', 'w', newline ='',encoding="utf-8")
with file: 
        
        # identifying header 
        header = [ 'ID', 'Attrition', 'YearsAtCompany']
        
        writer = csv.DictWriter(file, fieldnames = header) 
        # writing data row-wise into the csv file 
        writer.writeheader() 
        
        ran=[]
        answer=[]
        for i in range(3):
            ran.append(0)
            
        for l in range(0,240):
            ran[0] = ids[l]
            ran[1] = proans1[l]
            ran[2] = y_predtest2[l]
            answer.append(list(ran))
            for i in range(3):
                ran.append(0)
        
        for i in range(0,240):
            class my_dictionary(dict):
                
                # __init__ function  
                def __init__(self):  
                    self = dict()  
                # Function to add key:value  
                def add(self, key, value):  
                    self[key] = value    
            dict_obj = my_dictionary()  
            
            for j in range(0,3):
                dict_obj.add(head[j+1], answer[i][j]) 
                
            
            #print(dict_obj)
            writer.writerow(dict_obj)

In [52]:
print(np.concatenate((proans1.reshape(len(proans1),1), y_predtest2.reshape(len(y_predtest2),1)),1))

[[1.9e-01 3.0e+00]
 [3.5e-01 4.0e+00]
 [5.0e-02 3.0e+00]
 [3.3e-01 6.0e+00]
 [1.7e-01 4.0e+00]
 [3.0e-01 2.0e+00]
 [2.1e-01 6.0e+00]
 [6.0e-02 5.0e+00]
 [5.0e-02 1.5e+01]
 [1.0e-01 3.0e+00]
 [1.5e-01 2.0e+00]
 [2.7e-01 5.0e+00]
 [2.6e-01 3.0e+00]
 [3.9e-01 1.0e+00]
 [1.0e-02 1.4e+01]
 [1.8e-01 5.0e+00]
 [3.1e-01 2.0e+00]
 [1.3e-01 4.0e+00]
 [1.1e-01 3.0e+00]
 [1.6e-01 5.0e+00]
 [1.3e-01 1.1e+01]
 [1.9e-01 8.0e+00]
 [5.2e-01 1.0e+00]
 [2.5e-01 4.0e+00]
 [1.2e-01 1.0e+00]
 [2.0e-01 4.0e+00]
 [2.8e-01 8.0e+00]
 [1.8e-01 7.0e+00]
 [1.8e-01 2.0e+00]
 [9.0e-02 5.0e+00]
 [4.0e-01 5.0e+00]
 [3.6e-01 1.0e+00]
 [2.4e-01 1.0e+00]
 [2.7e-01 2.0e+00]
 [7.0e-02 1.3e+01]
 [3.3e-01 1.0e+00]
 [2.1e-01 1.0e+01]
 [3.0e-02 5.0e+00]
 [9.0e-02 2.0e+00]
 [3.0e-02 6.0e+00]
 [1.0e-02 1.6e+01]
 [4.0e-02 1.3e+01]
 [1.7e-01 8.0e+00]
 [1.3e-01 3.2e+01]
 [9.0e-02 3.0e+00]
 [2.1e-01 1.0e+00]
 [1.8e-01 4.0e+00]
 [2.1e-01 1.0e+00]
 [4.8e-01 1.0e+00]
 [2.2e-01 5.0e+00]
 [7.0e-02 9.0e+00]
 [4.4e-01 9.0e+00]
 [1.9e-01 8.